name: gollvm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build gollvm
      run: docker build . --file Dockerfile --tag gollvm:$(date +%s)
